### PR TITLE
Add Universal Lambda backend

### PR DESCRIPTION
**Pull request by woodrush**
This pull request adds a Universal Lambda backend.

Similar to #118 and #119, this backend uses [LambdaVM](https://github.com/woodrush/lambdavm) to implement the virtual machine.

LambdaVM is written as a program that runs natively on Binary Lambda Calculus (#118). As in the case with #119, this backend uses an [encoder-decoder](https://github.com/woodrush/lambdavm/blob/main/src/blc-clamb-wrapper.cl) layer so that LambdaVM can be run on Universal Lambda interpreters. The encoder-decoder is pre-compiled and built-in inside the backend's core, target/ulamb.c.

The test `make ulamb` finished successfully in 5 minutes on my machine from a fresh clone of this branch. This test omits 4 large programs that take some time, `out/8cc.c.eir.ulamb out/elc.c.eir.ulamb out/eli.c.eir.ulamb out/dump_ir.c.eir.ulamb`, but they are expected to run successfully as well since all the other programs run successfully.

`make test-ulamb-full` also runs successfully in 4 minutes on my machine. This test includes all of the programs in `test/`, including the ones that are omitted in `make ulamb`.

This backend uses @irori's Universal Lambda interpreter [clamb](https://github.com/irori/clamb). `tools/runulamb.sh` automatically clones and compiles this when running UL programs, in a way similar to the Unlambda backend.

### CODE REVIEW

**Comment by tromp** [comment]
The list of supported languages in the README.md also needs to be updated...

**Comment by woodrush** [comment]
I'll rebase this on the current master branch.

Also, I wanted to ask about what extension name to use for the outputs. #122 uses *.lam for the outputs. I believe some Universal Lambda programs use *.lam as well but I remember seeing other extensions as well, so my understanding is that there are various instances of extension names. Do you have a particular preference for the extension names? I'll refactor the variable names according to the extension as well.

**Comment by woodrush** [comment]
> The list of supported languages in the README.md also needs to be updated...

Sorry, I was missing that. I'll update the ones for UL when I rebase this branch.

**Comment by tromp** [comment]
I use .lam for symbolic lambda terms as accepted by my blc tool [1].

[1] https://github.com/tromp/AIT/blob/master/Lambda.lhs#L20-L102

**Comment by shinh** [comment]
> README.md

Yeah, I haven't merged this PR as I was planning to ask to add supported backends, but I forgot to post this message :)

**Comment by woodrush** [comment]
I see. I updated the language descriptions as well as some small cosmetic changes. I added some details for the Game of Life backend as well.

**Review by shinh — APPROVED** [review]
LGTM, thanks! Thanks for the details of these toughest backends!

**Comment by woodrush** [comment]
You're welcome! Delighted to know that you liked these backends!

**Pull request merged**
