### PR TITLE
Add Scala target

### PR DESCRIPTION
**Pull request by nwtgck**
## What I did

I implemented Scala target.

## Confirmation

Here is commands to confirm whether the target works or not.

```bash
./out/8cc -S -I. -Ilibc -I8cc/include -o 8cc.eir out/8cc.c
./out/elc -scala 8cc.eir > 8cc.scala
scalac -J-Xms256m -J-Xmx512m 8cc.scala
cat hello.c | scala Main
```

Then, I had ELVM IR of `hello.c`.

NOTE: `hello.c` should be prepared.

### CODE REVIEW

**Comment by shinh** [comment]
Thanks! It seems elc.c.eir.scala fails. Do you know the reason? To repro:

```
$ make -k scala
...
./runtest.sh out/elc.c.eir.scala.out tools/runscala.sh out/elc.c.eir.scala
java.lang.ClassFormatError: StackMapTable format error: bad verification type
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
build.mk:5: recipe for target 'out/elc.c.eir.scala.out' failed
make: *** [out/elc.c.eir.scala.out] Error 1
make: Target 'scala' not remade because of errors.
```

Is this just for me? It's fine to leave the issue as is. I'll just disable the test for scala target and look into the cause later.

**Comment by nwtgck** [comment]
@shinh , Thank you very much for merging!

## My terminal log

I just tried `make -k scala`. But I didn't have any error. 
Here is my terminal log.

[2018-04-25-elvm-make-k-scala.terminal_log](https://gist.github.com/nwtgck/8ee96338d4b3d111f0d0b7168d45d028#file-2018-04-25-elvm-make-k-scala-terminal_log)

## My testing environment

I'm not sure what "java.lang.ClassFormatError: StackMapTable format error" is. But, I guess that it can be triggered by differences of Scala version and JVM version.

This is my enviroment

```bash
[elvm]$ scala -version
Scala code runner version 2.12.3 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
```

```bash
[elvm]$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by shinh** [comment]
Yeah, I was suspecting my environment, too. Mine were

```
Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
```

I'd guess I need to use Oracle's JVM. I'll try it later. Anyway, thanks for the PR and the answer!

**Comment by nwtgck** [comment]
In my experience, sometimes, the combination of JDK 9 and Scala causes error. If you use JDK 8 instead of 9, the error may disappear.

**Pull request merged**
